const sponsors = [
  {
    name: "Eclipse",
    logo_url: "https://m.opencon.dev/static/ECLIPSE_BNnew.png",
    url: "https://www.eclipse.org/",
    width: "282px",
    height: "91px",
  },
  {
    name: "Gruppo Fos",
    logo_url: "https://m.opencon.dev/static/GRUPPOFOS_BNnew.png",
    url: "https://www.gruppofos.it/",
    width: "282px",
    height: "102px",
  },
  {
    name: "Telmekom",
    logo_url: "https://m.opencon.dev/static/TELMEKOM_BNnew.png",
    url: "http://www.telmekom.net/",
    width: "284px",
    height: "86px",
  },
  {
    name: "Vates",
    logo_url: "https://m.opencon.dev/static/VATES_BNnew.png",
    url: "http://www.telmekom.net/",
    width: "180px",
    height: "53.43px",
  },
  {
    name: "Colabora",
    logo_url: "https://m.opencon.dev/static/COLLABORA_BNnew.png",
    url: "https://www.collabora.com/",
    width: "180px",
    height: "71.16px",
  },
  {
    name: "Made In Chima",
    logo_url: "https://m.opencon.dev/static/MADEINCIMA_BNnew.png",
    url: "https://www.madeincima.it/",
    width: "128px",
    height: "70px",
  },
  {
    name: "1006 Org",
    logo_url: "https://m.opencon.dev/static/1006org_logonew.png",
    url: "https://www.madeincima.it/",
    width: "101px",
    height: "20px",
  },
  {
    name: "Catchsolve",
    logo_url: "https://m.opencon.dev/static/CATCHSOLVE_BNnew.png",
    url: "https://www.catch-solve.tech/",
    width: "128px",
    height: "32px",
  },
  {
    name: "Endian",
    logo_url: "https://m.opencon.dev/static/ENDIAN_BNnew.png",
    url: "https://www.endian.com/",
    width: "90px",
    height: "22.28px",
  },
  {
    name: "Peer",
    logo_url: "https://m.opencon.dev/static/Peer_BNnew.png",
    url: "https://www.peer.biz/de/",
    width: "80px",
    height: "30.66px",
  },
  {
    name: "Foss Life",
    logo_url: "https://m.opencon.dev/static/FossLife_BNnew.png",
    url: "https://fosslife.org/",
    width: "40px",
    height: "50.91px",
  },
  {
    name: "Fsfe",
    logo_url: "https://m.opencon.dev/static/FSFE_BNnew.png",
    url: "https://fsfe.org/",
    width: "70px",
    height: "38px",
  },
  {
    name: "Icsob",
    logo_url: "https://m.opencon.dev/static/ICSOB_BNnew.png",
    url: "https://icsob2022.github.io/",
    width: "46px",
    height: "38px",
  },
  {
    name: "Linux",
    logo_url: "https://m.opencon.dev/static/LinuxMagazine_BNnew.png",
    url: "https://www.linux-magazine.com/",
    width: "60px",
    height: "27px",
  },
  {
    name: "Lugbz",
    logo_url: "https://m.opencon.dev/static/LUGBZ_BNnew.png",
    url: "https://www.lugbz.org/",
    width: "36px",
    height: "42px",
  },
  {
    name: "Ow2",
    logo_url: "https://m.opencon.dev/static/OW2_BNnew.png",
    url: "https://www.ow2.org/",
    width: "50px",
    height: "13px",
  },
  {
    name: "Speck & Tech",
    logo_url: "https://m.opencon.dev/static/SpeckTech_BNnew.png",
    url: "https://speckand.tech/",
    width: "36px",
    height: "46px",
  },
  {
    name: "Sticker Mule",
    logo_url: "https://m.opencon.dev/static/Stickermule_BNnew.png",
    url: "https://www.stickermule.com/it/uses/laptop-stickers?utm_source=sponsorship&utm_medium=referral&utm_campaign=SFSCon21",
    width: "64px",
    height: "39px",
  },
  {
    name: "Unibz",
    logo_url: "https://m.opencon.dev/static/UNIBZ_BNnew.png",
    url: "https://www.unibz.it/",
    width: "46px",
    height: "36px",
  },
];

export default sponsors;
